services:
  jupyter-notebook-service:
    container_name: jupyter-notebook-container
    image: jupyter-notebook-spark:v0.1
    volumes:
      - ~/MyGithub/DS_Spark_Experiments/data:/home/jovyan/data
      - ~/MyGithub/DS_Spark_Experiments/work:/home/jovyan/work
    ports:
      - "8888:8888" # Spark Session
      - "4040:4040" # Spark UI port
