services:
  jupyter-pyspark:
    image: jupyter/pyspark-notebook:latest
    build: .
    volumes:
      - ./data:/home/jovyan/data
      - ./work:/home/jovyan/work
    ports:
      - "8888:8888" # Spark Session
      - "4040:4040" # Spark UI port
